name: "Article review with AI"
on:
  pull_request:
    types:
      - opened
    paths:
      - articles/*.md
      - books/**/*.md

jobs:
  review:
    permissions:
      models: read
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        with:
          files: |
            articles/**
            books/**

      - name: Inference
        id: inference
        uses: actions/ai-inference@d645f067d89ee1d5d736a5990e327e504d1c5a4a # v1.1.0
        if: steps.changed-files-specific.outputs.all_changed_files != ''
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files-specific.outputs.all_changed_files }}
        with:
          system-prompt: |
            あなたはテックブログのエキスパートです。
            あなたはブログ記事を内容の正確さ・読み手への伝わりやすさという点でレビューを行い、執筆者へフィードバックを提供します。
          prompt-file: "${{ env.ALL_CHANGED_FILES }}"

      - name: Comment on PullRequest
        id: comment
        if: steps.changed-files-specific.outputs.all_changed_files != ''
        env:
          RESPONSE: ${{ steps.inference.outputs.response }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ env.RESPONSE }}" > /tmp/comment
          gh pr comment ${{ github.event.pull_request.number }} -F /tmp/comment
